### ISSUE TITLE
Unable to recompile minecraft

### ISSUE THREAD

**Issue by Itzyo** [BaseMC/Aves#29]
Hello,
I am trying to recompile the code, generated with the tool. I want to get more debug output and later modify things again for debugging purposes (I am trying to write a custom server). The thing is that I can not recompile the code. 

Now here is my question. Is it even possible to recompile the code and if yes, how can I do so?

I appreciate your help,
Itzyo

**Comment by litetex** [comment]
The project uses for default decompiliation fernflower (stated [here](https://github.com/BaseMC/avesflower)).
I could't find a 100% working decompiler; fernflower is already pretty good and it works for 99% of the code but there are a few parts where it don't works.
If you know a better java decompiler (that works 100%), you can configure it [here](https://github.com/BaseMC/Aves/blob/develop/Aves/Config/Configuration.cs#L103-L130)

Generally the project is mainly meant to quickly generate some (mostly) readable source code, e.g. if a new version of Minecraft is released.
https://github.com/BaseMC/Aves#why

So this is more a "read-only" tool.

<br/>

If you wan't to do modifications to Minecraft I can recommend [Forge](https://mcforge.readthedocs.io/en/1.14.x/) or [Fabric](https://fabricmc.net/).
These rather try to "bind" the modification to an already existing Minecraft executable (on the end-users PC), which is also safer in licensing aspects, because you can't modify Minecraft and redistribute it (stated [here](https://github.com/BaseMC/Aves#requirements) and [here](https://account.mojang.com/documents/minecraft_eula)).

**Comment by Itzyo** [comment]
Thank you for your quick and helpful response.

I think based on your project, I can figure something out.
